### ISSUE TITLE
🎨 Expand User Profile Functionality with Theme Customization and UX Options

### ISSUE THREAD

**Issue by PapaBear1981** [PapaBear1981/SupplyLine-MRO-Suite#224]
# Enhanced User Profile with Customization Options

## 🎯 Objective
Expand the user profile functionality to include comprehensive theme customization, user experience preferences, and personalization options to improve user engagement and satisfaction.

## 🔍 Current State
- Basic profile modal with limited functionality
- Simple light/dark theme toggle
- Basic user information display
- Limited preference options

### Theme Customization
1. **Color Schemes**:
   - Expand beyond light/dark to include color themes
   - Add predefined color schemes (Blue, Green, Purple, Orange, Red)
   - Allow custom accent color selection
   - Implement theme preview functionality

2. **Layout Options**:
   - Compact vs. Comfortable spacing
   - Sidebar width preferences
   - Table density options (compact, normal, comfortable)
   - Font size preferences (small, normal, large)

### User Experience Preferences
3. **Notification Settings**:
   - Email notification preferences
   - In-app notification settings
   - Sound notification toggle
   - Notification frequency settings

4. **Dashboard Customization**:
   - Widget visibility toggles
   - Dashboard layout preferences
   - Quick action customization
   - Default page on login

5. **Data Display Preferences**:
   - Date format preferences (MM/DD/YYYY, DD/MM/YYYY, YYYY-MM-DD)
   - Time format (12-hour vs 24-hour)
   - Number format preferences
   - Default items per page in tables

### Advanced Features
6. **Accessibility Options**:
   - High contrast mode
   - Reduced motion preferences
   - Screen reader optimizations
   - Keyboard navigation preferences

7. **Productivity Features**:
   - Auto-save form preferences
   - Default checkout duration
   - Favorite tools/chemicals quick access
   - Recent items history length

### Enhanced ProfileModal Structure
```jsx
<Modal show={show} onHide={onHide} size="lg" centered>
  <Modal.Header closeButton>
    <Modal.Title>User Profile & Preferences</Modal.Title>
  </Modal.Header>
  <Modal.Body>
    <Tabs defaultActiveKey="profile" className="mb-3">
      <Tab eventKey="profile" title="Profile">
        {/* User info, avatar, basic settings */}
      </Tab>
      <Tab eventKey="appearance" title="Appearance">
        {/* Theme, colors, layout options */}
      </Tab>
      <Tab eventKey="preferences" title="Preferences">
        {/* UX preferences, notifications, defaults */}
      </Tab>
      <Tab eventKey="accessibility" title="Accessibility">
        {/* Accessibility options */}
      </Tab>
      <Tab eventKey="help" title="Help & Tours">
        {/* Help system controls */}
      </Tab>
    </Tabs>
  </Modal.Body>
</Modal>
```

### New Redux Slice for User Preferences
```jsx
// userPreferencesSlice.js
const initialState = {
  theme: 'light',
  colorScheme: 'blue',
  layout: 'comfortable',
  tableDensity: 'normal',
  fontSize: 'normal',
  dateFormat: 'MM/DD/YYYY',
  timeFormat: '12-hour',
  itemsPerPage: 25,
  notifications: {
    email: true,
    inApp: true,
    sound: false
  },
  dashboard: {
    showQuickActions: true,
    showRecentActivity: true,
    showAnnouncements: true
  },
  accessibility: {
    highContrast: false,
    reducedMotion: false
  }
};
```

### CSS Custom Properties for Theming
```css
:root {
  /* Base colors */
  --primary-color: #007bff;
  --secondary-color: #6c757d;
  --success-color: #28a745;
  --warning-color: #ffc107;
  --danger-color: #dc3545;
  
  /* Theme-specific colors */
  --bg-primary: #ffffff;
  --bg-secondary: #f8f9fa;
  --text-primary: #212529;
  --text-secondary: #6c757d;
  
  /* Layout variables */
  --spacing-unit: 1rem;
  --border-radius: 0.375rem;
  --font-size-base: 1rem;
  --table-row-height: 3rem;
}

[data-color-scheme="green"] {
  --primary-color: #28a745;
}

[data-color-scheme="purple"] {
  --primary-color: #6f42c1;
}

[data-layout="compact"] {
  --spacing-unit: 0.5rem;
  --table-row-height: 2.5rem;
}
```

### Phase 1: Core Infrastructure
- [ ] Create userPreferencesSlice Redux store
- [ ] Implement preference persistence to localStorage/backend
- [ ] Create enhanced ProfileModal with tabs
- [ ] Set up CSS custom properties system

### Phase 2: Appearance Customization
- [ ] Implement color scheme selection
- [ ] Add layout density options
- [ ] Create font size controls
- [ ] Add theme preview functionality

### Phase 3: User Experience Preferences
- [ ] Add notification settings
- [ ] Implement dashboard customization
- [ ] Add data format preferences
- [ ] Create default behavior settings

### Phase 4: Accessibility Features
- [ ] Implement high contrast mode
- [ ] Add reduced motion preferences
- [ ] Create keyboard navigation options
- [ ] Add screen reader optimizations

### Phase 5: Advanced Features
- [ ] Add productivity preferences
- [ ] Implement favorite items system
- [ ] Create custom quick actions
- [ ] Add export/import preferences

### Phase 6: Testing & Polish
- [ ] Test all theme combinations
- [ ] Verify accessibility compliance
- [ ] Test preference persistence
- [ ] Ensure mobile compatibility

## 📊 Success Criteria
- [ ] Users can fully customize their visual experience
- [ ] Preferences persist across sessions and devices
- [ ] All customizations work on mobile and desktop
- [ ] Accessibility options meet WCAG guidelines
- [ ] Performance impact is minimal
- [ ] User satisfaction with customization options increases

## 🔗 Related Issues
- Part of #221 (v3.5.5 Roadmap)
- Related to #223 (Help System in Profile)
- Supports #225 (Mobile Optimization)

## 📝 Notes
- Consider user onboarding for new customization features
- Implement sensible defaults for all preferences
- Ensure themes work well with existing components
- Consider adding preset "profiles" for different user types
- Plan for future expansion of customization options
