### ISSUE TITLE
📱 Create Dedicated Mobile Pages for Tablets and Phones

### ISSUE THREAD

**Issue by PapaBear1981** [PapaBear1981/SupplyLine-MRO-Suite#225]
# Mobile-Optimized Pages and Components

## 🎯 Objective
Create dedicated mobile-optimized pages and components specifically designed for tablets and phones to provide a superior mobile user experience compared to the current responsive design.

## 🔍 Current State
- Application works on mobile devices but is clumsy
- Desktop-first design doesn't translate well to mobile
- Small touch targets and cramped layouts
- Limited mobile-specific CSS (only for cycle count functionality)
- No mobile-specific navigation patterns

### Mobile Detection and Routing
1. **Device Detection**:
   - Implement device detection utility
   - Create mobile-specific routing logic
   - Add user preference to force desktop/mobile view
   - Handle orientation changes gracefully

2. **Mobile-First Components**:
   - Create mobile versions of key components
   - Implement touch-friendly interactions
   - Add swipe gestures where appropriate
   - Optimize for thumb navigation

### Mobile Navigation
3. **Bottom Navigation Bar**:
   - Replace top navigation with bottom tab bar
   - Include: Dashboard, Tools, Checkouts, Profile
   - Add floating action button for quick actions
   - Implement badge notifications

4. **Mobile Header**:
   - Simplified header with app title
   - Search icon and notifications
   - Hamburger menu for secondary actions
   - User avatar for profile access

### Mobile-Optimized Pages
5. **Dashboard (Mobile)**:
   - Card-based layout with swipeable sections
   - Condensed information display
   - Quick action buttons prominently placed
   - Pull-to-refresh functionality

6. **Tool Management (Mobile)**:
   - List view with large touch targets
   - Swipe actions for quick operations
   - Simplified search and filters
   - Barcode scanner integration

7. **Checkout System (Mobile)**:
   - Streamlined checkout flow
   - Large buttons and form fields
   - Camera integration for tool photos
   - Offline capability for field use

8. **Chemical Management (Mobile)**:
   - Grid view with chemical photos
   - Touch-friendly quantity adjustments
   - Quick issue functionality
   - Expiration date highlights

### Mobile-Specific Features
9. **Progressive Web App (PWA)**:
   - Add service worker for offline functionality
   - Implement app manifest for installation
   - Add push notifications
   - Cache critical resources

10. **Mobile Interactions**:
    - Pull-to-refresh on lists
    - Swipe-to-delete/archive
    - Long-press context menus
    - Haptic feedback where supported

### Device Detection Hook
```jsx
// hooks/useDeviceDetection.js
export const useDeviceDetection = () => {
  const [deviceType, setDeviceType] = useState('desktop');
  const [orientation, setOrientation] = useState('portrait');
  
  useEffect(() => {
    const checkDevice = () => {
      const width = window.innerWidth;
      const height = window.innerHeight;
      const userAgent = navigator.userAgent;
      
      if (width <= 768) {
        setDeviceType('mobile');
      } else if (width <= 1024) {
        setDeviceType('tablet');
      } else {
        setDeviceType('desktop');
      }
      
      setOrientation(width > height ? 'landscape' : 'portrait');
    };
    
    checkDevice();
    window.addEventListener('resize', checkDevice);
    return () => window.removeEventListener('resize', checkDevice);
  }, []);
  
  return { deviceType, orientation };
};
```

### Mobile Layout Component
```jsx
// components/mobile/MobileLayout.jsx
const MobileLayout = ({ children }) => {
  return (
    <div className="mobile-layout">
      <MobileHeader />
      <main className="mobile-content">
        {children}
      </main>
      <MobileBottomNav />
    </div>
  );
};
```

### Mobile Bottom Navigation
```jsx
// components/mobile/MobileBottomNav.jsx
const MobileBottomNav = () => {
  const location = useLocation();
  
  const navItems = [
    { path: '/dashboard', icon: 'house', label: 'Home' },
    { path: '/tools', icon: 'tools', label: 'Tools' },
    { path: '/checkouts', icon: 'clipboard-check', label: 'Checkouts' },
    { path: '/profile', icon: 'person', label: 'Profile' }
  ];
  
  return (
    <nav className="mobile-bottom-nav">
      {navItems.map(item => (
        <Link 
          key={item.path}
          to={item.path}
          className={`nav-item ${location.pathname === item.path ? 'active' : ''}`}
        >
          <i className={`bi bi-${item.icon}`}></i>
          <span>{item.label}</span>
        </Link>
      ))}
    </nav>
  );
};
```

### Mobile-Specific Styles
```css
/* styles/mobile.css */
.mobile-layout {
  display: flex;
  flex-direction: column;
  height: 100vh;
  overflow: hidden;
}

.mobile-content {
  flex: 1;
  overflow-y: auto;
  padding-bottom: 80px; /* Space for bottom nav */
  -webkit-overflow-scrolling: touch;
}

.mobile-bottom-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 80px;
  background: var(--bg-primary);
  border-top: 1px solid var(--border-color);
  display: flex;
  justify-content: space-around;
  align-items: center;
  z-index: 1000;
}

.mobile-bottom-nav .nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 8px;
  min-width: 60px;
  text-decoration: none;
  color: var(--text-secondary);
  transition: color 0.2s;
}

.mobile-bottom-nav .nav-item.active {
  color: var(--primary-color);
}

.mobile-bottom-nav .nav-item i {
  font-size: 1.2rem;
  margin-bottom: 4px;
}

.mobile-bottom-nav .nav-item span {
  font-size: 0.75rem;
}

/* Touch-friendly buttons */
.mobile-layout .btn {
  min-height: 44px;
  padding: 12px 16px;
  font-size: 1rem;
}

.mobile-layout .btn-sm {
  min-height: 36px;
  padding: 8px 12px;
}

/* Mobile cards */
.mobile-card {
  margin-bottom: 1rem;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.mobile-card-header {
  padding: 1rem;
  background: var(--bg-secondary);
  border-bottom: 1px solid var(--border-color);
}

.mobile-card-body {
  padding: 1rem;
}

/* Swipe actions */
.swipe-container {
  position: relative;
  overflow: hidden;
}

.swipe-actions {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  display: flex;
  transform: translateX(100%);
  transition: transform 0.3s ease;
}

.swipe-container.swiped .swipe-actions {
  transform: translateX(0);
}

.swipe-action {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 80px;
  color: white;
  font-size: 1.2rem;
}

.swipe-action.delete {
  background: var(--danger-color);
}

.swipe-action.edit {
  background: var(--warning-color);
}
```

### Phase 1: Core Mobile Infrastructure
- [ ] Create device detection hook
- [ ] Implement mobile routing logic
- [ ] Create MobileLayout component
- [ ] Build mobile bottom navigation
- [ ] Set up mobile-specific CSS framework

### Phase 2: Mobile Navigation and Header
- [ ] Create MobileHeader component
- [ ] Implement hamburger menu
- [ ] Add search functionality for mobile
- [ ] Create notification system for mobile
- [ ] Add user profile access

### Phase 3: Mobile Dashboard
- [ ] Create mobile dashboard layout
- [ ] Implement card-based design
- [ ] Add pull-to-refresh functionality
- [ ] Create mobile quick actions
- [ ] Optimize dashboard widgets for mobile

### Phase 4: Mobile Tool Management
- [ ] Create mobile tool list component
- [ ] Implement swipe actions
- [ ] Add mobile tool detail view
- [ ] Create mobile tool forms
- [ ] Integrate barcode scanner

### Phase 5: Mobile Checkout System
- [ ] Create mobile checkout flow
- [ ] Implement touch-friendly forms
- [ ] Add camera integration
- [ ] Create offline checkout capability
- [ ] Optimize checkout history for mobile

### Phase 6: Mobile Chemical Management
- [ ] Create mobile chemical list
- [ ] Implement grid view with photos
- [ ] Add mobile chemical forms
- [ ] Create quick issue functionality
- [ ] Add expiration alerts for mobile

### Phase 7: PWA Features
- [ ] Implement service worker
- [ ] Create app manifest
- [ ] Add offline functionality
- [ ] Implement push notifications
- [ ] Add install prompts

### Phase 8: Mobile Interactions
- [ ] Implement pull-to-refresh
- [ ] Add swipe gestures
- [ ] Create long-press menus
- [ ] Add haptic feedback
- [ ] Optimize touch targets

### Phase 9: Testing and Optimization
- [ ] Test on various mobile devices
- [ ] Optimize performance for mobile
- [ ] Test offline functionality
- [ ] Verify touch interactions
- [ ] Test PWA installation

## 📊 Success Criteria
- [ ] Mobile experience feels native and responsive
- [ ] All core functionality works seamlessly on mobile
- [ ] Touch targets meet accessibility guidelines (44px minimum)
- [ ] App can be installed as PWA
- [ ] Offline functionality works for critical features
- [ ] Mobile performance is smooth (60fps interactions)
- [ ] User satisfaction with mobile experience increases significantly

## 🔗 Related Issues
- Part of #221 (v3.5.5 Roadmap)
- Supports #224 (User Profile Customization)
- Related to #222 (Tooltip Standardization)

## 📝 Notes
- Consider progressive enhancement approach
- Ensure feature parity between desktop and mobile
- Plan for tablet-specific optimizations
- Consider offline-first design for field workers
- Test extensively on real devices, not just browser dev tools
