### ISSUE TITLE
🎨 Consolidate and Unify CSS Theme System

### ISSUE THREAD

**Issue by PapaBear1981** [PapaBear1981/SupplyLine-MRO-Suite#230]
# CSS Theme System Consolidation

## 🎯 Objective
Consolidate the multiple conflicting CSS files and create a unified theme system that works consistently across the entire application.

## 🔍 Current Problem
The application currently has **multiple conflicting CSS theme systems** that don't work together:

### Conflicting CSS Files:
1. **`backend/static/style.css`**:
   - Has its own CSS custom properties theme system
   - Uses `--primary-color: #4a90e2` (light blue)
   - Includes dark theme with `[data-theme="dark"]`
   - Has color scheme variants (blue, green, purple)
   - **Problem**: This is backend static CSS that may not be loaded in React frontend

2. **`frontend/src/App.css`**:
   - Uses Bootstrap's default colors
   - Has custom styling for cards, tables, buttons
   - **Problem**: Doesn't use the custom properties from backend CSS

3. **`frontend/src/index.css`**:
   - Has its own theme system with `[data-bs-theme="dark"]`
   - Uses Bootstrap CSS custom properties
   - Defines status badge colors
   - **Problem**: Different theme attribute than backend (`data-bs-theme` vs `data-theme`)

4. **`frontend/src/styles/mobile.css`**:
   - Mobile-specific styles for cycle count functionality
   - Uses hardcoded colors instead of CSS custom properties
   - **Problem**: Not integrated with main theme system

### Color Inconsistencies:
- **Backend Primary**: `#4a90e2` (light blue)
- **Frontend Primary**: `#0d6efd` (Bootstrap blue)
- **Mobile Styles**: Hardcoded `#007bff` and `#0056b3`
- **Status Colors**: Different across files

### 1. Single Source of Truth
- Create one unified CSS custom properties system
- Remove duplicate and conflicting CSS
- Ensure all components use the same color variables

### 2. Consistent Theme Attributes
- Standardize on either `data-theme` or `data-bs-theme`
- Ensure theme switching works across all components
- Support both light and dark themes consistently

### 3. Color System Unification
- Choose one primary color and stick to it
- Create consistent status color palette
- Ensure accessibility (contrast ratios)
- Support multiple color schemes (blue, green, purple, etc.)

### 4. Mobile Integration
- Integrate mobile styles with main theme system
- Ensure mobile components respect theme settings
- Remove hardcoded colors from mobile CSS

### Phase 1: Audit and Cleanup
1. **Remove Unused CSS**:
   - Determine if `backend/static/style.css` is actually used
   - Remove duplicate styles across files
   - Identify which styles are actually needed

2. **Standardize Theme Attributes**:
   - Choose between `data-theme` and `data-bs-theme`
   - Update all CSS selectors to use consistent attribute
   - Update JavaScript theme switching logic

### Phase 2: Create Unified Theme System
1. **Create Master CSS Variables File**:
   ```css
   /* themes/variables.css */
   :root {
     /* Brand Colors */
     --primary-color: #0d6efd;
     --secondary-color: #6c757d;
     --success-color: #198754;
     --info-color: #0dcaf0;
     --warning-color: #ffc107;
     --danger-color: #dc3545;
     
     /* Theme Colors */
     --bg-primary: #ffffff;
     --bg-secondary: #f8f9fa;
     --text-primary: #212529;
     --text-secondary: #6c757d;
     --border-color: #dee2e6;
     
     /* Component Colors */
     --navbar-bg: var(--bg-primary);
     --card-bg: var(--bg-primary);
     --table-bg: var(--bg-primary);
     
     /* Status Colors */
     --status-available: var(--success-color);
     --status-checked-out: var(--warning-color);
     --status-maintenance: var(--info-color);
     --status-retired: var(--danger-color);
   }
   
   [data-bs-theme="dark"] {
     --bg-primary: #212529;
     --bg-secondary: #343a40;
     --text-primary: #ffffff;
     --text-secondary: #adb5bd;
     --border-color: #495057;
   }
   
   [data-color-scheme="green"] {
     --primary-color: #198754;
   }
   
   [data-color-scheme="purple"] {
     --primary-color: #6f42c1;
   }
   ```

2. **Update Component Styles**:
   - Replace hardcoded colors with CSS custom properties
   - Ensure all components respect theme variables
   - Test theme switching functionality

### Phase 3: Integration and Testing
1. **Update Theme Context**:
   - Ensure React theme context uses correct attributes
   - Update theme switching logic
   - Test persistence across page reloads

2. **Mobile Theme Integration**:
   - Update mobile.css to use theme variables
   - Ensure mobile components respect theme settings
   - Test theme switching on mobile devices

## 📝 File Structure Proposal

```
frontend/src/styles/
├── themes/
│   ├── variables.css          # Master CSS custom properties
│   ├── light-theme.css        # Light theme overrides
│   ├── dark-theme.css         # Dark theme overrides
│   └── color-schemes.css      # Color scheme variants
├── components/
│   ├── buttons.css            # Button styling
│   ├── forms.css              # Form styling
│   ├── tables.css             # Table styling
│   └── cards.css              # Card styling
├── layout/
│   ├── navigation.css         # Navigation styling
│   └── layout.css             # Layout utilities
├── mobile.css                 # Mobile-specific styles
└── index.css                  # Main stylesheet imports
```

### Phase 1: Cleanup
- [ ] Audit all CSS files and identify conflicts
- [ ] Determine which backend CSS is actually used
- [ ] Remove duplicate styles
- [ ] Standardize theme attribute (`data-bs-theme`)
- [ ] Update theme switching JavaScript

### Phase 2: Unification
- [ ] Create master CSS variables file
- [ ] Update all components to use CSS custom properties
- [ ] Remove hardcoded colors from all CSS files
- [ ] Create consistent color scheme system
- [ ] Test theme switching functionality

### Phase 3: Mobile Integration
- [ ] Update mobile.css to use theme variables
- [ ] Ensure mobile components respect themes
- [ ] Test mobile theme switching
- [ ] Verify mobile accessibility

### Phase 4: Testing
- [ ] Test all themes across all components
- [ ] Verify color contrast accessibility
- [ ] Test theme persistence
- [ ] Cross-browser testing
- [ ] Mobile device testing

## 📊 Success Criteria
- [ ] Single, consistent theme system across entire application
- [ ] No conflicting CSS files or duplicate styles
- [ ] Theme switching works on all components
- [ ] Mobile components respect theme settings
- [ ] All colors meet accessibility contrast requirements
- [ ] Performance is not negatively impacted
- [ ] Easy to add new color schemes in the future

## 🔗 Related Issues
- Part of #221 (v3.5.5 Roadmap)
- Critical for #224 (User Profile Theme Customization)
- Supports #229 (Real UI/UX Inconsistencies)
- Foundation for #225 (Mobile Optimization)

## 📝 Notes
- This is a foundational issue that should be completed early in v3.5.5
- Will require careful testing to ensure no visual regressions
- Consider creating a theme preview tool for testing
- Document the new theme system for future developers
- Plan for gradual migration to avoid breaking changes
